version: "3"

services: 
    php-apache:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/var/www/html
            # - ..:/workspace:cached
        ports:
            - "8080:80"
        # ports:
        #     # For use with PHP (e.g. `php -S localhost:8080`)
        #     - "8080:8080"
        # command: sleep infinity
        networks: 
            - php-apache
    # php-apache:
    #     image: php:7.4-apache
    #     ports:
    #         - "80:80"
    #     volumes: 
    #         - ./src:/var/www/html    
    #     links:
    #         - mariadb    
    mariadb:
        image: mariadb:10.4
        volumes:
            - db_data:/var/lib/mysql
        restart: on-failure
        expose:
            # Expose mariadb port to php service (Access as hostname "mariadb" from within php container)
            - "3306"
        # Uncomment to allow access to mariadb from external tools
        # ports:
        #     - "3306:3306"
        networks:
            - php-apache
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: phonetics
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - php-apache
            - mariadb
        links:
            - "mariadb:db"
        ports:
            - 8081:80  
        networks: 
            - php-apache
        environment:
            PMA_HOST: mariadb
volumes:
    db_data:
networks: 
    php-apache:

